name: albarka_p2p_wallet
description: ALBARKA P2P WALLET - non-custodial wallet
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  web3dart: ^3.0.3
  http: ^1.4.0
  flutter_secure_storage: ^9.2.4
  qr_flutter: ^4.1.0
  hd_wallet_kit: ^0.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

